trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  timeoutInMinutes: 0

steps:
- script: docker info && docker --version
  displayName: 'Run infrastructure tests'
  env:
    CX_INFRA_IT_CF_PASSWORD: $(cfPassword)
    CX_INFRA_IT_CF_USERNAME: $(cfUsername)
